### ISSUE TITLE
Suggestion for CLA handling

### ISSUE THREAD

**Issue by agraebe** [uber/rides-java-sdk#11]
Hi,

I saw that you require contributors to sign the Uber CLA separately. How about simply adding CLA assistant: https://cla-assistant.io/ to the repo?

**Comment by arogal** [comment]
We are currently discussing what we'd like to do in this area. We'll stick
with the CLA signing using the google form for now, but I'll put this as a
suggestion for the future.

**Comment by agraebe** [comment]
Thanks! 👍
