### ISSUE TITLE
default to Environment.SANDBOX

### ISSUE THREAD

**Issue by MarianoTucat** [uber/rides-java-sdk#2]
I think Environment.SANDBOX should be used by default, when no environment is set.
I have just made a real request by mistake (my mistake) of omitting the environment.
That would not have happened If it was set by default to SANDBOX.

**Comment by noonhub** [comment]
Thanks for the feedback. We are taking into consideration and will let you know what design we land on. Regardless of that outcome, I think that clearer and more prominent documentation around the exact behavior will help to avoid future confusion.

**Comment by threecSAP** [comment]
I still don't know how to run it in the eclipse,could you please tell me how to import it into Eclipse and run the sample? Thanks a lot

**Comment by itstexter** [comment]
Fixed with release of v0.2.0
