### ISSUE TITLE
[Task] Required update to include ride receipts and add scope surge_accept

### ISSUE THREAD

**Issue by vineetpatil** [uber/rides-java-sdk#6]
1. Uber SDK version 0.2.0 added the scope request_receipt but there is no implementation to get the receipts of the rides.
2. Please add scope "surge_accept" to enum Scopes.

**Comment by mnemonicflow** [comment]
1. See PR #7 
2. According to the [Scopes](https://developer.uber.com/docs/scopes) documentation there is no "surge_accept" scope.

**Comment by vineetpatil** [comment]
Great thanks for implementing the rides receipt.
I will close this issue now.
